CREATE DATABASE bdpratica02;
USE bdpratica02;
CREATE TABLE DEPARTAMENTO(
	COD_DEPART INT(4),
    NOME VARCHAR(30) NOT NULL,
    DATA_INICIAL DATE,
    CONSTRAINT pk_cod_depart 
    PRIMARY KEY (COD_DEPART)
);
CREATE TABLE LOCALIZACAO (
	COD_DEPART INT(4),
    LOC_LOCAL VARCHAR(252),
    CONSTRAINT pk_localizacao
    PRIMARY KEY (COD_DEPART, LOC_LOCAL),
    CONSTRAINT fk_cod_depart
    FOREIGN KEY (COD_DEPART)
    REFERENCES DEPARTAMENTO (COD_DEPART)
);
CREATE TABLE FUNCIONARIO (
    COD_FUNC INT (4),
    NOME VARCHAR (30) NOT NULL,
    CPF VARCHAR(15) UNIQUE,
    SALARIO DECIMAL(6,2),
    ENDERECO VARCHAR(252),
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'F')),
    COD_SUPER INT(4),
    COD_DEPART INT(4),
    CONSTRAINT pk_funcionario 
    PRIMARY KEY (COD_FUNC), 
    CONSTRAINT fk_supervisor_funcionario 
    FOREIGN KEY (COD_SUPER) 
    REFERENCES FUNCIONARIO (COD_FUNC),
    CONSTRAINT fk_departamento 
    FOREIGN KEY (COD_DEPART) 
    REFERENCES DEPARTAMENTO (COD_DEPART),
    CONSTRAINT validar_salario
    CHECK (SALARIO >=1000.00)
);

CREATE TABLE DEPENDENTE(
	COD_FUNC INT(4),
    SEQ INT (4),
    NOME VARCHAR(100) NOT NULL,
    PARENTESCO VARCHAR(30) NOT NULL,
    DATA_NASC DATE,
    CONSTRAINT pk_dependente
    PRIMARY KEY (COD_FUNC, SEQ),
    CONSTRAINT fk_cod_func 
    FOREIGN KEY (COD_FUNC)
    REFERENCES FUNCIONARIO (COD_FUNC), 
    CONSTRAINT verificar_parentesco
    CHECK(PARENTESCO = 'PAI' OR PARENTESCO = 'MÃE' OR PARENTESCO = 'IRMÃOS' OR PARENTESCO = 'FILHO')
);
CREATE TABLE PROJETO (
	COD_PROJ INT (4),
    COD_DEPART INT (4),
    TITULO VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(252),
    DATA_CAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_projeto
    PRIMARY KEY (COD_PROJ),
    CONSTRAINT fk_departamento_projeto
    FOREIGN KEY (COD_DEPART)
    REFERENCES DEPARTAMENTO (COD_DEPART)
);

CREATE TABLE PARTICIPA(
	COD_FUNC INT(4),
    COD_PROJ INT (4),
    HORAS VARCHAR(50),
    CONSTRAINT pk_participa
    PRIMARY KEY (COD_FUNC, COD_PROJ),
    CONSTRAINT fk_funcionario
    FOREIGN KEY (COD_FUNC)
    REFERENCES FUNCIONARIO(COD_FUNC),
    CONSTRAINT fk_projeto
    FOREIGN KEY (COD_PROJ)
    REFERENCES PROJETO(COD_PROJ)
);

ALTER TABLE PROJETO 
ADD STATUS INT (1) not NULL CHECK (STATUS IN (0, 1));

ALTER TABLE PROJETO
modify TITULO VARCHAR(155) NOT NULL;

ALTER TABLE PROJETO
CHANGE COLUMN DATA_CAD DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE ENDERECO(
	ID BIGINT PRIMARY KEY,
    RUA VARCHAR (100) NOT NULL,
    NUMERO INT (4) NOT NULL, 
    BAIRRO VARCHAR (50) NOT NULL, 
    CIDADE VARCHAR(50) NOT NULL, 
    ESTADO VARCHAR (50) NOT NULL,
    CEP VARCHAR (10) NOT NULL, 
    CONSTRAINT unique_keys
    unique key (RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP)
    );
    
ALTER TABLE FUNCIONARIO 
DROP COLUMN ENDERECO;

CREATE TABLE FUNC_END(
	COD_FUNC INT (4),
    COD_END BIGINT,
    CONSTRAINT PK_FUNC_END
    primary key (COD_FUNC, COD_END),
    constraint FK_COD_FUNC_END
    foreign key (COD_FUNC) references FUNCIONARIO (COD_FUNC),
    constraint FK_COD_END
    foreign key (COD_END) references ENDERECO (ID)
    );

ALTER TABLE FUNCIONARIO 
DROP CONSTRAINT validar_salario;

CREATE TABLE PARENTESCO(
	COD_PARENTESCO BIGINT,
    DESCRICAO VARCHAR (30) NOT NULL,
    primary key (COD_PARENTESCO),
	CONSTRAINT verificar_descricao
    CHECK(DESCRICAO = 'PAI' OR DESCRICAO = 'MÃE' OR DESCRICAO = 'IRMÃOS' OR DESCRICAO = 'FILHO')    
    );

ALTER TABLE DEPENDENTE
DROP COLUMN PARENTESCO;

ALTER TABLE DEPENDENTE
ADD COLUMN COD_PARENTESCO BIGINT;

ALTER TABLE DEPENDENTE 
ADD CONSTRAINT FK_COD_PARENTESCO_DEPENDENTE FOREIGN KEY (COD_PARENTESCO) REFERENCES PARENTESCO (COD_PARENTESCO);

ALTER TABLE DEPENDENTE 
ADD COLUMN CPF_DEPENDENTE VARCHAR (15) UNIQUE;

ALTER TABLE DEPENDENTE
DROP CONSTRAINT fk_cod_func,
ADD CONSTRAINT fk_cod_func_dependente FOREIGN KEY (COD_FUNC) references FUNCIONARIO (COD_FUNC) ON DELETE CASCADE;

RENAME TABLE PARTICIPA TO FUNC_PROJETO;

    

	
    



